### ISSUE TITLE
Automatization of labels in GitHub Actions

### ISSUE THREAD

**Issue by Erick-0M** [ShiqiYang2022/template#11]
Follow the https://github.com/gentzkow/template/issues/84#issuecomment-1724716114.

**Comment by ShiqiYang2022** [comment]
@Erick11293 How is it going? Shall we wrap up this by the end of the week? Thanks!!

**Comment by ShiqiYang2022** [comment]
Oh actually github is much more efficient than slack.

**Comment by Erick-0M** [comment]
I completely agree. I'll work on this at the end of the day. Tomorrow, I'll get an update.

**Comment by ShiqiYang2022** [comment]
Perfect! Love you :snake:

Let me know when you need me to test this new automation on my end.

**Comment by ShiqiYang2022** [comment]
I am wondering apart from what we already updated, can we let the workflow itself to identify whether this is a blank repo. If this is a blank repo, we can push directly. If not, we can do as what we have now in Github Action, clone, checkout and push.

**Comment by Erick-0M** [comment]
@ShiqiYang2022 I had the same idea, and I tried to do that on my test on Monday. Sadly, I think github actions are not allowed to create branches, or at least not using the code we have your instructions. We can explore this option if we have time.

**Comment by ShiqiYang2022** [comment]
@Erick11293 I think I have complete the upgrading Wiki, see [here](https://github.com/ShiqiYang2022/template/wiki/Overleaf%E2%80%90GitHub-Synchronization), to make it clearer to implement. Do you have time to do a test tomorrow on the Automation part _strictly follow_ the new instructions? I think 1 hour at most would be enough. 

Thanks!

**Comment by ShiqiYang2022** [comment]
Per conversation, @jc-cisneros will test the newly updated [automation process](https://github.com/ShiqiYang2022/template/wiki/Overleaf%E2%80%90GitHub-Synchronization#automation) using his template. Ideally it will work(and it should work!). Feel free to put comments here(informal comment is very acceptable and welcomed!). Ideally we shall not spend no more than 1 hour. 

Thanks chief!  :crown:

**Comment by jc-cisneros** [comment]
@ShiqiYang2022 per our conversations in Slack, now the process is working in both directions. Great work! 
I do think the setup process is still not trivial. I would particularly add more explicit details on the SSH section. 

Some minor points:
- We currently get both "success"/"failed" messages for the Actions even if it is working as expected.
- An annoying side effect of the previous point, is that I get bombarded by e-mails. I considerable subset of those are actually inaccurate.

**Comment by ShiqiYang2022** [comment]
@jc-cisneros Thanks for your time to test!

I agree 100% we should make the setup process more clear and it's exactly the purpose of testing. I have updated the new instructions [here](https://github.com/ShiqiYang2022/template/wiki/Overleaf%E2%80%90GitHub-Synchronization#automation). If you have time could you please take a look at it?

**Comment by ShiqiYang2022** [comment]
Close this issue as completed.

**Summary:**

Final delivarble can be found [here](https://github.com/ShiqiYang2022/template/wiki/Overleaf%E2%80%90GitHub-Synchronization#automation)
