### ISSUE TITLE
Tests new PDF export from CSV

### ISSUE THREAD

**Issue by snairdesai** [ShiqiYang2022/template#19]
@ShiqiYang2022: Let me know if you see any issues here, or come across any problems. Thanks for testing! Instructions are below:

1. Clone the `template` repository, and switch to the branch [`85_ditab_format`](https://github.com/gentzkow/template/tree/85_ditab_format).
2. Create the `config_user.yaml` file and initialize `git lfs` as usual.
3. Build and activate the `conda` environment. I had to add a couple of `Python` packages for the automated export to PDF to compile, so you may need to delete and rebuild the environment if you have an older version stored locally:

```
    conda env remove -n template
    conda config --set channel_priority strict
    conda env create -f setup/conda_env.yaml
```

4. Initialize and update the submodule as usual. Then, navigate to `~/lib/gslab_make` and switch to the branch `template85_ditab_format`.

5. Execute `python run_all.py` from root. This will populate the placeholder scalars when running the `analysis` module, and produce the formatted PDF tables when running `paper_slides`.

6. You should see the populated PDFs with the proper formatting now live in `~/paper_slides/output`. They are the files prefixed with `gs_` (see [here](https://github.com/gentzkow/template/tree/85_ditab_format/paper_slides/output)).

---

A few notes:

- The first time you run this, Excel will open on your computer and may prompt you to enable file access for the folder where you have cloned the repository. You should only need to do this once (the first time you execute `run_all.py`).
-  After you execute `run_all.py` for the first time to populate the outputs from the `~/analysis` module, you can make desired formatting edits to the Excel sheets in the `~/paper_slides/skeleton` folder, and (assuming the link references are also properly updated), the formatting will update if you run only `~/paper_slides`.

**Comment by ShiqiYang2022** [comment]
Confirm it works, thanks for the good work here @snairdesai ! I made an edit for typo in your comment.
